# CategoryRAG系统版本映射配置
# 定义集合ID到版本信息的映射关系

# 版本映射配置
version_mapping:
  # 集合到版本信息的映射
  collections:
    report_1104_2024:
      name: "1104报表_2024版"
      version: "2024版"
      display_name: "[2024版]"
      type: "监管报表"
      priority: 1
      description: "银行业监管统计报表制度2024年版"
      
    report_1104_2022:
      name: "1104报表_2022版"
      version: "2022版"
      display_name: "[2022版]"
      type: "监管报表"
      priority: 2
      description: "银行业监管统计报表制度2022年版"
      
    pboc_statistics:
      name: "人民银行金融统计制度汇编"
      version: "现行版"
      display_name: "[人民银行统计制度]"
      type: "统计制度"
      priority: 1
      description: "人民银行金融统计制度汇编现行版本"
      
    east_data_structure:
      name: "EAST数据结构"
      version: "现行版"
      display_name: "[EAST数据结构]"
      type: "数据结构"
      priority: 1
      description: "EAST系统数据结构说明文档"
      
    east_metadata:
      name: "EAST元数据说明"
      version: "现行版"
      display_name: "[EAST元数据]"
      type: "元数据"
      priority: 1
      description: "EAST系统元数据说明文档"
      
    ybt_data_structure:
      name: "一表通数据结构"
      version: "现行版"
      display_name: "[一表通数据结构]"
      type: "数据结构"
      priority: 1
      description: "一表通系统数据结构说明文档"
      
    ybt_product_mapping:
      name: "一表通产品报送映射"
      version: "现行版"
      display_name: "[一表通产品映射]"
      type: "产品映射"
      priority: 1
      description: "一表通产品报送映射关系文档"
      
    default:
      name: "默认集合"
      version: "混合版本"
      display_name: "[默认集合]"
      type: "混合"
      priority: 999
      description: "默认文档集合"

  # 版本组配置（用于版本对比）
  version_groups:
    "1104报表":
      collections:
        - report_1104_2024
        - report_1104_2022
      latest: report_1104_2024
      description: "银行业监管统计报表制度"
      
    "EAST系统":
      collections:
        - east_data_structure
        - east_metadata
      latest: east_data_structure
      description: "EAST监管数据报送系统"
      
    "一表通系统":
      collections:
        - ybt_data_structure
        - ybt_product_mapping
      latest: ybt_data_structure
      description: "一表通产品报送系统"

  # 版本检测规则
  detection_rules:
    explicit_version:
      "2024": ["report_1104_2024"]
      "2022": ["report_1104_2022"]
      "最新": ["report_1104_2024", "pboc_statistics", "east_data_structure", "ybt_data_structure"]
      "新版": ["report_1104_2024"]
      "旧版": ["report_1104_2022"]
      
    comparison_keywords:
      - "对比"
      - "比较"
      - "差异"
      - "区别"
      - "变化"
      - "相比"
      
    ambiguous_patterns:
      - "涉及.*表"
      - "包含.*表"
      - "哪些.*表"
      - "报送表.*列表"
      - "表格.*名称"

# 版本处理策略
version_strategies:
  default_strategy: "prefer_latest"  # prefer_latest | ask_user | include_all
  
  strategies:
    prefer_latest:
      description: "优先使用最新版本"
      fallback: "ask_user"
      
    ask_user:
      description: "询问用户版本偏好"
      timeout: 30  # 秒
      
    include_all:
      description: "包含所有相关版本"
      max_versions: 3
